# Generated by Django 3.1.2 on 2020-10-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClientName', models.CharField(max_length=265)),
                ('first_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=32)),
                ('mobile', models.CharField(max_length=16)),
                ('persion', models.CharField(max_length=64)),
                ('mobile1', models.CharField(max_length=16)),
                ('license_key', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('zipcode', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
            ],
        ),
    ]
