# Generated by Django 3.1.2 on 2020-10-09 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Select_Student', models.CharField(blank=True, max_length=265, null=True)),
                ('Student_First_Name', models.CharField(blank=True, max_length=265, null=True)),
                ('Student_Middle_Name', models.CharField(blank=True, max_length=265, null=True)),
                ('Student_Last_Name', models.CharField(blank=True, max_length=265, null=True)),
                ('Student_Email', models.CharField(blank=True, max_length=265, null=True)),
                ('Student_Mobile', models.CharField(blank=True, max_length=265, null=True)),
                ('Emergency_Contact_Person1', models.CharField(blank=True, max_length=265, null=True)),
                ('Emergency_Mobile1', models.CharField(blank=True, max_length=265, null=True)),
                ('Relationship_1', models.CharField(blank=True, choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Relative', 'Relative '), ('Friend', 'Friend')], max_length=265, null=True)),
                ('Emergency_Contact_Person2', models.CharField(blank=True, max_length=265, null=True)),
                ('Emergency_Mobile2', models.CharField(blank=True, max_length=265, null=True)),
                ('Relationship_2', models.CharField(blank=True, choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Relative', 'Relative '), ('Friend', 'Friend')], max_length=265, null=True)),
                ('Student_Address', models.CharField(blank=True, max_length=265, null=True)),
                ('City', models.CharField(blank=True, max_length=265, null=True)),
                ('State', models.CharField(blank=True, max_length=265, null=True)),
                ('Zip_Code', models.CharField(blank=True, max_length=265, null=True)),
                ('Country', models.CharField(blank=True, max_length=265, null=True)),
                ('gate_student', models.CharField(blank=True, max_length=265, null=True)),
                ('Current_School_Attending', models.CharField(blank=True, max_length=265, null=True)),
                ('School_District', models.CharField(blank=True, max_length=265, null=True)),
                ('Grade_Level', models.CharField(blank=True, max_length=265, null=True)),
                ('GAP', models.CharField(blank=True, max_length=265, null=True)),
                ('Additional_Comments', models.CharField(blank=True, max_length=265, null=True)),
                ('Enroll_Program', models.CharField(blank=True, max_length=265, null=True)),
                ('Assign_Teachers', models.CharField(blank=True, max_length=265, null=True)),
                ('Continuing_Student', models.CharField(blank=True, max_length=265, null=True)),
                ('Discount_Applied_Code', models.CharField(blank=True, max_length=265, null=True)),
                ('Exit_Program', models.CharField(blank=True, max_length=265, null=True)),
                ('Exit_Comments', models.CharField(blank=True, max_length=265, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Select_Teacher', models.CharField(blank=True, max_length=265, null=True)),
                ('Prefix', models.CharField(blank=True, choices=[('Dr.', 'Dr.'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms')], max_length=265, null=True)),
                ('First_Name', models.CharField(blank=True, max_length=265, null=True)),
                ('Middle_Name', models.CharField(blank=True, max_length=265, null=True)),
                ('Last_Name', models.CharField(blank=True, max_length=265, null=True)),
                ('Email', models.CharField(blank=True, max_length=265, null=True)),
                ('Mobile', models.CharField(blank=True, max_length=265, null=True)),
                ('Emergency_Contact_Person1', models.CharField(blank=True, max_length=265, null=True)),
                ('Emergency_Mobile1', models.CharField(blank=True, max_length=265, null=True)),
                ('Relationship_1', models.CharField(blank=True, choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Relative', 'Relative '), ('Friend', 'Friend')], max_length=265, null=True)),
                ('Emergency_Contact_Person2', models.CharField(blank=True, max_length=265, null=True)),
                ('Emergency_Mobile2', models.CharField(blank=True, max_length=265, null=True)),
                ('Relationship_2', models.CharField(blank=True, choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Relative', 'Relative '), ('Friend', 'Friend')], max_length=265, null=True)),
                ('Address', models.CharField(blank=True, max_length=265, null=True)),
                ('City', models.CharField(blank=True, max_length=265, null=True)),
                ('State', models.CharField(blank=True, max_length=265, null=True)),
                ('Zip_Code', models.CharField(blank=True, max_length=265, null=True)),
                ('Country', models.CharField(blank=True, max_length=265, null=True)),
                ('School_District', models.CharField(blank=True, max_length=265, null=True)),
                ('Currently_Teaching', models.CharField(blank=True, max_length=265, null=True)),
                ('Ap_Classess', models.CharField(blank=True, max_length=265, null=True)),
                ('Notes_Comments', models.CharField(blank=True, max_length=265, null=True)),
                ('High_Degree_Completed', models.CharField(blank=True, max_length=265, null=True)),
                ('Grade_Level', models.CharField(blank=True, max_length=265, null=True)),
                ('Speciality', models.CharField(blank=True, max_length=265, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='ClientName',
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='license_key',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='middle_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile1',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='persion',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='zipcode',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='ClientAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(blank=True, max_length=265, null=True)),
                ('LastName', models.CharField(blank=True, max_length=265, null=True)),
                ('Email', models.CharField(blank=True, max_length=265, null=True)),
                ('licence', models.CharField(blank=True, max_length=265, null=True)),
                ('loginEmail', models.CharField(blank=True, max_length=265, null=True)),
                ('password', models.CharField(blank=True, max_length=265, null=True)),
                ('Client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='AdminClassroomAssignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Courses_Taught', models.CharField(blank=True, max_length=265, null=True)),
                ('Select_Students', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.studentprofile')),
                ('Select_Teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.teacherprofile')),
            ],
        ),
    ]
