# Generated by Django 3.1.2 on 2020-11-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_clientadmin_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminclassroomassignments',
            name='Select_Students',
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AlterField(
            model_name='adminclassroomassignments',
            name='Select_Teacher',
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
    ]
