# Generated by Django 3.1.2 on 2020-11-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201102_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='Relationship_1',
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='Relationship_2',
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='Prefix',
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='Relationship_1',
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='Relationship_2',
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
    ]
