# Generated by Django 3.1.2 on 2020-11-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_studentprofile_academy_magnet_cbse'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='Password',
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
    ]
