# Generated by Django 2.2.10 on 2020-11-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_studentprofile_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Select_Student', models.CharField(blank=True, max_length=265, null=True)),
                ('Select_Program', models.CharField(blank=True, max_length=265, null=True)),
                ('Available_Test', models.CharField(blank=True, max_length=265, null=True)),
                ('View_By', models.CharField(blank=True, max_length=265, null=True)),
            ],
        ),
    ]
