# Generated by Django 2.2.10 on 2020-11-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_answerbank_dataquestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerbank',
            name='steps_steps_video',
        ),
        migrations.AddField(
            model_name='answerbank',
            name='step_1_image',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='answerbank',
            name='step_2_image',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='answerbank',
            name='Step_3',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='answerbank',
            name='all_steps',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='answerbank',
            name='all_steps_image',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='answerbank',
            name='answer_source_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='answerbank',
            name='description_long',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='answerbank',
            name='description_short',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='answerbank',
            name='filler_1',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='answerbank',
            name='step_1',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='answerbank',
            name='step_2',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='answerbank',
            name='step_3_image',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='answerbank',
            name='step_4',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='answerbank',
            name='step_4_image',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='answerbank',
            name='steps_video',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
