# Generated by Django 2.2.10 on 2020-11-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20201122_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataquestions',
            old_name='description_longh',
            new_name='description_long',
        ),
        migrations.RenameField(
            model_name='dataquestions',
            old_name='section_optional_count',
            new_name='section_optional',
        ),
        migrations.AddField(
            model_name='dataquestions',
            name='section_question_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
