# Generated by Django 2.2.10 on 2020-11-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20201122_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataquestions',
            name='answer_1',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='dataquestions',
            name='answer_2',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='dataquestions',
            name='answer_3',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='dataquestions',
            name='answer_4',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='dataquestions',
            name='filter_1',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='dataquestions',
            name='question_header',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='dataquestions',
            name='question_image',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='dataquestions',
            name='question_text',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
